num = int(input('Escreva um número: '))
print ('{} x {} = {}'.format(num , 1 , num * 1))
print ('{} x {} = {}'.format(num , 2 , num * 2))
print ('{} x {} = {}'.format(num , 3 , num * 3))
print ('{} x {} = {}'.format(num , 1 , num * 4))
print ('{} x {} = {}'.format(num , 1 , num * 5))
print ('{} x {} = {}'.format(num , 1 , num * 6))
print ('{} x {} = {}'.format(num , 1 , num * 7))
print ('{} x {} = {}'.format(num , 1 , num * 8))
print ('{} x {} = {}'.format(num , 1 , num * 9))
print ('{} x {} = {}'.format(num , 1 , num * 10))
print ('Está é a tabuada de {}'.format (num))